export type MarketingVisual =
  | "schedule"
  | "impact"
  | "documents"
  | "lookahead"
  | "field"
  | "weekly"
  | "risk"
  | "portfolio"
  | "analytics"
  | "ai"
  | "role"
  | "integration";

export type MarketingPageData = {
  slug: string;
  section: "Features" | "Solutions";
  group: string;
  title: string;
  headline: string;
  description: string;
  visual: MarketingVisual;
  visualLabel: string;
  outcomes: readonly [string, string, string];
  highlights: readonly [
    { title: string; body: string },
    { title: string; body: string },
    { title: string; body: string },
  ];
  workflow: readonly [
    { title: string; body: string },
    { title: string; body: string },
    { title: string; body: string },
    { title: string; body: string },
  ];
  proof: { value: string; label: string; title: string; body: string };
};

export const featurePages: Record<string, MarketingPageData> = {
  "master-schedule": {
    slug: "master-schedule",
    section: "Features",
    group: "Scheduling",
    title: "Master Schedule",
    headline: "Build the plan everyone can actually run.",
    description: "Create a logic-driven construction schedule, protect milestones, and keep every downstream plan connected as work changes.",
    visual: "schedule",
    visualLabel: "Live contract schedule",
    outcomes: ["Logic-linked activities", "Critical path visibility", "Baseline variance tracking"],
    highlights: [
      { title: "Schedule with context", body: "Connect activities, milestones, trades, documents, and constraints in one operating plan." },
      { title: "See change before delay", body: "Float, dependency, and variance signals surface the work that needs attention first." },
      { title: "Keep the field connected", body: "Lookaheads and weekly plans stay tied to the current master schedule instead of drifting into spreadsheets." },
    ],
    workflow: [
      { title: "Import or start clean", body: "Bring in an existing plan or build a schedule around your project milestones." },
      { title: "Link the logic", body: "Sequence work with dependencies, durations, calendars, and trade ownership." },
      { title: "Set the baseline", body: "Capture the approved plan and measure every meaningful shift against it." },
      { title: "Update from the field", body: "Roll actual progress and constraints back into the plan without rebuilding it." },
    ],
    proof: { value: "1 plan", label: "from contract to crew", title: "A schedule should be an operating system, not a monthly artifact.", body: "Agira makes the master schedule useful between updates by connecting it directly to short-interval planning and project controls." },
  },
  "schedule-impact-requests": {
    slug: "schedule-impact-requests",
    section: "Features",
    group: "Scheduling",
    title: "Schedule Impact Requests",
    headline: "Turn field change into a decision, not a surprise.",
    description: "Capture emerging impacts with evidence, ownership, and schedule context before they become unexplained delay.",
    visual: "impact",
    visualLabel: "Impact review queue",
    outcomes: ["Traceable change requests", "Schedule-linked evidence", "Faster review cycles"],
    highlights: [
      { title: "Document the moment", body: "Record the condition, affected work, photos, and responsible party while details are fresh." },
      { title: "Quantify the exposure", body: "Tie each request to activities and milestones so teams can assess real schedule consequence." },
      { title: "Close the decision loop", body: "Route reviews, capture decisions, and preserve a clean history for every impact." },
    ],
    workflow: [
      { title: "Raise the request", body: "Field or project teams log a changed condition from the work itself." },
      { title: "Attach the facts", body: "Add dates, photos, notes, documents, and affected schedule activities." },
      { title: "Review the impact", body: "Project leaders assess time exposure and assign the next action." },
      { title: "Resolve and record", body: "Approve, reject, or mitigate with a decision history that stays searchable." },
    ],
    proof: { value: "0 gaps", label: "between event and record", title: "The best delay record starts before the delay.", body: "A consistent impact workflow gives project teams the evidence and schedule context needed to act early and explain decisions later." },
  },
  submittals: {
    slug: "submittals",
    section: "Features",
    group: "Scheduling",
    title: "Submittals",
    headline: "Manage approvals by when the work needs them.",
    description: "Connect every submittal to procurement and installation dates so document status reflects schedule risk, not just workflow status.",
    visual: "documents",
    visualLabel: "Schedule-linked submittal log",
    outcomes: ["Need-by date control", "Activity-linked records", "Approval risk visibility"],
    highlights: [
      { title: "Work backward from install", body: "Calculate review and procurement urgency from the actual schedule need date." },
      { title: "Prioritize what matters", body: "Focus teams on overdue and at-risk approvals instead of scanning an undifferentiated log." },
      { title: "Keep one document trail", body: "Store reviewers, revisions, dates, and decisions alongside the affected work." },
    ],
    workflow: [
      { title: "Create the register", body: "Organize packages by spec section, trade, and responsible company." },
      { title: "Connect activities", body: "Link each item to procurement, delivery, or installation work." },
      { title: "Track the review", body: "Monitor submission, response, revision, and approval milestones." },
      { title: "Escalate risk", body: "Surface approvals that threaten upcoming work before crews are waiting." },
    ],
    proof: { value: "Need-by", label: "instead of due someday", title: "Document control becomes project control when dates are connected.", body: "Agira gives every submittal a schedule consequence, helping teams act on the approvals that protect production." },
  },
  rfis: {
    slug: "rfis",
    section: "Features",
    group: "Scheduling",
    title: "RFIs",
    headline: "See which unanswered question can stop the job.",
    description: "Track RFIs against affected activities, required response dates, and field commitments to reveal schedule exposure early.",
    visual: "documents",
    visualLabel: "RFI risk register",
    outcomes: ["Schedule-aware priority", "Clear response ownership", "Field-ready answers"],
    highlights: [
      { title: "Connect question to work", body: "Link an RFI directly to the activity, location, drawing, and crew it can affect." },
      { title: "Set the real need date", body: "Manage response priority from planned work rather than the age of the RFI alone." },
      { title: "Turn answers into action", body: "Notify the right people and carry the resolution into the live plan." },
    ],
    workflow: [
      { title: "Capture the question", body: "Log the issue with location, drawings, photos, and trade context." },
      { title: "Map the exposure", body: "Associate affected activities and define the date an answer is required." },
      { title: "Drive the response", body: "Track assignment, status, aging, and follow-up from one queue." },
      { title: "Release the work", body: "Record the answer and clear or adjust the related constraint." },
    ],
    proof: { value: "One view", label: "of question and consequence", title: "Not every open RFI is urgent. The schedule tells you which is.", body: "Agira helps project teams separate administrative backlog from questions that can affect production this week." },
  },
  lookahead: {
    slug: "lookahead",
    section: "Features",
    group: "Field coordination",
    title: "Lookahead Planning",
    headline: "Make the next six weeks buildable.",
    description: "Pull work from the master schedule, sequence it with the field, and expose every prerequisite before it reaches the weekly plan.",
    visual: "lookahead",
    visualLabel: "Six-week lookahead",
    outcomes: ["Rolling planning window", "Trade-ready sequencing", "Constraint screening"],
    highlights: [
      { title: "Stay tied to the master", body: "Upcoming work flows from the live schedule with dates and logic intact." },
      { title: "Plan at field detail", body: "Break activities into workable handoffs, locations, crews, and daily sequences." },
      { title: "Make ready before commit", body: "Check labor, material, design, access, and predecessor constraints in advance." },
    ],
    workflow: [
      { title: "Pull upcoming work", body: "Bring the next two to six weeks into a focused planning view." },
      { title: "Sequence together", body: "Coordinate trade handoffs and location flow with field leadership." },
      { title: "Screen constraints", body: "Identify what must be cleared for each activity to be executable." },
      { title: "Promote ready work", body: "Move reliable commitments into the weekly plan with context attached." },
    ],
    proof: { value: "6 weeks", label: "of shared foresight", title: "Reliable weekly work begins with a buildable lookahead.", body: "Agira turns the gap between a high-level CPM schedule and daily coordination into a visible, repeatable planning process." },
  },
  "field-tracking": {
    slug: "field-tracking",
    section: "Features",
    group: "Field coordination",
    title: "Field Tracking",
    headline: "Capture progress where the work happens.",
    description: "Give field teams a fast, focused way to update progress, add evidence, and flag issues without navigating the full schedule.",
    visual: "field",
    visualLabel: "Mobile field update",
    outcomes: ["Fast mobile updates", "Photo-backed progress", "Live office visibility"],
    highlights: [
      { title: "Built for the jobsite", body: "Simple task lists and large controls make updates practical from a phone or tablet." },
      { title: "Add proof, not paperwork", body: "Attach photos and concise notes to the exact activity and location." },
      { title: "Update the shared plan", body: "Office teams see production and emerging risk without waiting for another meeting." },
    ],
    workflow: [
      { title: "Open today's work", body: "See assigned and active tasks organized by area, trade, or plan." },
      { title: "Record progress", body: "Update quantity, percent complete, or status in a few taps." },
      { title: "Attach site context", body: "Add a photo, note, or blocker while standing at the work." },
      { title: "Sync the team", body: "Changes become visible across planning and project controls immediately." },
    ],
    proof: { value: "60 sec", label: "to report real progress", title: "Field data only helps when field teams will actually enter it.", body: "Agira reduces update friction while preserving the schedule context office teams need for reliable decisions." },
  },
  "weekly-work-plan": {
    slug: "weekly-work-plan",
    section: "Features",
    group: "Field coordination",
    title: "Weekly Work Plan",
    headline: "Turn coordination into clear commitments.",
    description: "Build a reliable weekly plan with trade owners, measurable promises, daily status, and automatic Percent Plan Complete.",
    visual: "weekly",
    visualLabel: "Current weekly plan",
    outcomes: ["Trade commitments", "Daily plan control", "Automatic PPC"],
    highlights: [
      { title: "Commit to ready work", body: "Only pull activities whose prerequisites have been checked and cleared." },
      { title: "Run the week visibly", body: "Track planned and actual completion across crews, days, and work areas." },
      { title: "Learn from variance", body: "Capture reasons for incomplete work and turn them into planning improvements." },
    ],
    workflow: [
      { title: "Select ready tasks", body: "Promote executable work from the lookahead into the weekly plan." },
      { title: "Confirm ownership", body: "Agree on crew, quantity, completion criteria, and day of work." },
      { title: "Track daily status", body: "Keep commitments current as work progresses throughout the week." },
      { title: "Review performance", body: "Calculate PPC and analyze reasons for variance in the same workflow." },
    ],
    proof: { value: "PPC", label: "calculated automatically", title: "A promise becomes useful when the team can learn from it.", body: "Agira connects commitment planning and performance measurement so teams improve reliability week after week." },
  },
  "roadblocks-constraints": {
    slug: "roadblocks-constraints",
    section: "Features",
    group: "Field coordination",
    title: "Roadblocks & Constraints",
    headline: "Clear the path before crews arrive.",
    description: "Track every prerequisite with an owner, need date, and affected work so constraints are removed before they become delay.",
    visual: "risk",
    visualLabel: "Constraint control center",
    outcomes: ["Make-ready screening", "Owner and due date", "Escalation by exposure"],
    highlights: [
      { title: "Standardize make-ready", body: "Check design, material, labor, equipment, access, safety, and predecessor readiness." },
      { title: "Assign the resolution", body: "Every roadblock gets a clear owner, next action, and date tied to planned work." },
      { title: "Escalate intelligently", body: "Prioritize open constraints by schedule exposure instead of chasing the longest list." },
    ],
    workflow: [
      { title: "Identify the blocker", body: "Raise constraints from the schedule, lookahead, field, RFI, or submittal log." },
      { title: "Link affected work", body: "Connect the issue to activities, locations, milestones, and responsible trades." },
      { title: "Drive the action", body: "Set ownership and follow the resolution through a focused queue." },
      { title: "Verify readiness", body: "Clear the constraint and return the activity to the executable plan." },
    ],
    proof: { value: "Before", label: "the planned start date", title: "A visible constraint is a problem the team can solve.", body: "Agira gives roadblocks the schedule context and ownership needed to move from discussion to resolution." },
  },
  "projects-timeline": {
    slug: "projects-timeline",
    section: "Features",
    group: "Portfolio management",
    title: "Projects Timeline",
    headline: "See every project on one shared horizon.",
    description: "Compare milestones, phases, and delivery exposure across the portfolio without opening schedules one by one.",
    visual: "portfolio",
    visualLabel: "Portfolio delivery timeline",
    outcomes: ["Cross-project milestones", "Portfolio date exposure", "Shared executive horizon"],
    highlights: [
      { title: "Normalize the portfolio", body: "View projects with consistent phases and milestones even when their schedules differ." },
      { title: "Spot collisions early", body: "See overlapping starts, turnover dates, and resource pressure across active work." },
      { title: "Move from summary to detail", body: "Drill from portfolio signals into the exact project and schedule activity." },
    ],
    workflow: [
      { title: "Connect active projects", body: "Roll live schedule dates into a shared portfolio view." },
      { title: "Align key milestones", body: "Map starts, phase gates, substantial completion, and turnover consistently." },
      { title: "Review exposure", body: "Compare variance and risk across the full delivery horizon." },
      { title: "Focus intervention", body: "Open the projects that need leadership attention with context preserved." },
    ],
    proof: { value: "All projects", label: "one delivery horizon", title: "Portfolio visibility should lead directly to project action.", body: "Agira keeps executive timelines connected to the live planning work beneath them." },
  },
  "executive-dashboard": {
    slug: "executive-dashboard",
    section: "Features",
    group: "Portfolio management",
    title: "Executive Dashboard",
    headline: "Know where to intervene before the report meeting.",
    description: "See schedule health, milestone movement, constraint exposure, and planning reliability across every active project.",
    visual: "portfolio",
    visualLabel: "Executive portfolio pulse",
    outcomes: ["Consistent project health", "Risk-ranked attention", "Live operational detail"],
    highlights: [
      { title: "One health language", body: "Compare projects through consistent measures instead of subjective status colors." },
      { title: "See leading indicators", body: "Use constraint aging and commitment reliability alongside milestone variance." },
      { title: "Trust the detail", body: "Move from a portfolio signal to the underlying task, owner, and action." },
    ],
    workflow: [
      { title: "Collect live signals", body: "Bring schedule, field, risk, and planning performance together automatically." },
      { title: "Rank attention", body: "Surface projects with the greatest delivery exposure or worsening trend." },
      { title: "Review the cause", body: "Drill into milestones, constraints, and recent variance without waiting for a report." },
      { title: "Track intervention", body: "Follow action ownership and improvement through the next reporting cycle." },
    ],
    proof: { value: "Live", label: "not last Friday's report", title: "Leadership visibility is only useful when it is operational.", body: "Agira replaces status collection with a direct view into the planning signals that drive project outcomes." },
  },
  analytics: {
    slug: "analytics",
    section: "Features",
    group: "Portfolio management",
    title: "Analytics",
    headline: "Turn planning behavior into better performance.",
    description: "Measure reliability, production trend, schedule variance, and recurring constraint patterns across projects and trades.",
    visual: "analytics",
    visualLabel: "Planning performance analytics",
    outcomes: ["PPC and PRR trends", "S-curve visibility", "Root-cause learning"],
    highlights: [
      { title: "Measure plan reliability", body: "Track commitments made, work completed, and reasons for variance over time." },
      { title: "See trend, not snapshots", body: "Compare baseline, planned, and actual progress with clear performance curves." },
      { title: "Learn across projects", body: "Find recurring blockers and trade patterns that deserve systemic improvement." },
    ],
    workflow: [
      { title: "Capture consistent data", body: "Use daily updates and weekly commitments as the source for performance signals." },
      { title: "Compare the plan", body: "Measure actual delivery against baseline and near-term promises." },
      { title: "Explain the variance", body: "Group reasons for incomplete work by cause, project, and trade." },
      { title: "Improve the system", body: "Use trends to focus coaching, planning, and process changes." },
    ],
    proof: { value: "+ trend", label: "behind every KPI", title: "The number matters. The direction and cause matter more.", body: "Agira keeps performance measures connected to the work and decisions that produced them." },
  },
  "ai-assistant": {
    slug: "ai-assistant",
    section: "Features",
    group: "Agent",
    title: "Agent",
    headline: "Ask the schedule. Get an answer you can verify.",
    description: "Find activities, explain risk, summarize changes, and prepare coordination answers grounded in your live project data.",
    visual: "ai",
    visualLabel: "Project-grounded assistant",
    outcomes: ["Cited project answers", "Faster schedule analysis", "Action-ready summaries"],
    highlights: [
      { title: "Grounded in your project", body: "Answers use current schedule, constraint, RFI, submittal, and planning records." },
      { title: "Show the source", body: "Open the underlying activity or record instead of trusting an unexplained response." },
      { title: "Move from answer to action", body: "Turn findings into follow-ups, meeting notes, or focused project reviews." },
    ],
    workflow: [
      { title: "Ask naturally", body: "Use the project language your team already uses, no query syntax required." },
      { title: "Search connected records", body: "The assistant examines relevant schedule and project-control context." },
      { title: "Review the evidence", body: "Answers include source records and the logic behind the conclusion." },
      { title: "Act in context", body: "Open the work, owner, or risk directly from the response." },
    ],
    proof: { value: "Cited", label: "answers, not guesses", title: "Construction AI should make project truth easier to reach.", body: "Agent is designed around traceability, giving teams a faster path to the information already inside their plan." },
  },
  "portfolio-qa": {
    slug: "portfolio-qa",
    section: "Features",
    group: "Agent",
    title: "Portfolio Q&A",
    headline: "Ask across every project in plain language.",
    description: "Compare milestone risk, open constraints, weekly reliability, and portfolio health without assembling another report.",
    visual: "ai",
    visualLabel: "Cross-project intelligence",
    outcomes: ["Cross-project answers", "Risk-ranked summaries", "Source-level drilldown"],
    highlights: [
      { title: "Ask one portfolio question", body: "Search current information across projects, teams, trades, and delivery dates." },
      { title: "Compare consistently", body: "Summaries use the same planning and risk language across the organization." },
      { title: "Follow every claim", body: "Drill into the project records behind each answer or highlighted exception." },
    ],
    workflow: [
      { title: "Frame the question", body: "Ask about delivery exposure, constraints, trade performance, or recent change." },
      { title: "Scan the portfolio", body: "Agira examines current project and planning signals together." },
      { title: "Rank the findings", body: "Results prioritize the projects and records most relevant to the question." },
      { title: "Open the evidence", body: "Move from summary to source without losing context." },
    ],
    proof: { value: "N projects", label: "one clear answer", title: "Portfolio intelligence should not require a reporting marathon.", body: "Agira makes operational project data directly accessible to the people making cross-project decisions." },
  },
};

export const solutionPages: Record<string, MarketingPageData> = {
  "project-managers": {
    slug: "project-managers",
    section: "Solutions",
    group: "By role",
    title: "Project Managers",
    headline: "Keep the plan, risk, and team moving together.",
    description: "Run coordination from one connected workspace instead of rebuilding project truth across schedules, logs, spreadsheets, and meeting notes.",
    visual: "role",
    visualLabel: "Project manager command view",
    outcomes: ["One coordination system", "Earlier risk visibility", "Less report preparation"],
    highlights: [
      { title: "Run from one plan", body: "Connect schedule, lookahead, commitments, RFIs, submittals, and constraints." },
      { title: "Know what needs action", body: "See upcoming decisions and owners ranked by delivery exposure." },
      { title: "Report without rebuilding", body: "Use live project signals for owner reviews and stakeholder updates." },
    ],
    workflow: [
      { title: "Review the horizon", body: "Start with upcoming milestones, variance, and unresolved constraints." },
      { title: "Coordinate the details", body: "Align field, design, trade, and procurement actions around the schedule." },
      { title: "Run the commitments", body: "Track weekly promises and resolve incomplete work quickly." },
      { title: "Communicate the truth", body: "Share current status with direct links to the underlying work." },
    ],
    proof: { value: "One workspace", label: "for the project operating rhythm", title: "Project managers should manage the project, not assemble its data.", body: "Agira keeps planning and project controls connected so coordination work produces reporting automatically." },
  },
  schedulers: {
    slug: "schedulers",
    section: "Solutions",
    group: "By role",
    title: "Schedulers",
    headline: "Protect the logic without losing the field.",
    description: "Maintain a disciplined master schedule while bringing actual progress, constraints, and weekly planning into every update.",
    visual: "schedule",
    visualLabel: "Scheduler control workspace",
    outcomes: ["Cleaner update cycles", "Field-informed progress", "Defensible variance"],
    highlights: [
      { title: "Keep logic visible", body: "Work with dependencies, float, baselines, and milestone movement in a focused schedule view." },
      { title: "Collect better updates", body: "Use field progress and commitment status instead of chasing disconnected notes." },
      { title: "Explain the movement", body: "Connect schedule change to impacts, constraints, and actual project events." },
    ],
    workflow: [
      { title: "Review current status", body: "See field updates, completion evidence, and open questions before the update." },
      { title: "Validate the logic", body: "Resolve sequencing and date conflicts with project and field teams." },
      { title: "Record the update", body: "Advance progress while preserving baseline and variance history." },
      { title: "Publish downstream", body: "Refresh lookaheads and portfolio signals from the approved schedule." },
    ],
    proof: { value: "Less chase", label: "more schedule analysis", title: "A better update begins with better project inputs.", body: "Agira brings field planning and project controls into the scheduler's workflow without weakening schedule discipline." },
  },
  superintendents: {
    slug: "superintendents",
    section: "Solutions",
    group: "By role",
    title: "Superintendents",
    headline: "Plan the work. Clear the path. Run the week.",
    description: "Coordinate trades, sequence locations, remove constraints, and keep the office current from a practical field-first workspace.",
    visual: "field",
    visualLabel: "Field planning board",
    outcomes: ["Field-ready lookaheads", "Visible trade promises", "Fast constraint ownership"],
    highlights: [
      { title: "Build a workable sequence", body: "Turn schedule activities into the location and trade detail crews need." },
      { title: "Make work ready", body: "Check material, design, access, labor, equipment, and predecessor conditions." },
      { title: "Run daily from the plan", body: "Update commitments, progress, photos, and roadblocks without duplicate entry." },
    ],
    workflow: [
      { title: "Shape the lookahead", body: "Sequence upcoming work with the people closest to production." },
      { title: "Clear constraints", body: "Assign prerequisites before they threaten a crew's start." },
      { title: "Confirm the week", body: "Agree on ready work and measurable trade commitments." },
      { title: "Learn every Friday", body: "Review PPC and reasons for variance to improve the next plan." },
    ],
    proof: { value: "Field first", label: "without disconnecting the schedule", title: "The best plan is the one the field can use every day.", body: "Agira keeps field planning practical while preserving the schedule connection project teams depend on." },
  },
  "trade-partners": {
    slug: "trade-partners",
    section: "Solutions",
    group: "By role",
    title: "Trade Partners",
    headline: "Give every trade a clear promise and a clear path.",
    description: "Let trade partners see upcoming work, confirm commitments, report progress, and raise constraints without learning another complicated system.",
    visual: "weekly",
    visualLabel: "Trade commitment view",
    outcomes: ["Clear weekly promises", "Simple self-updates", "Earlier prerequisite signals"],
    highlights: [
      { title: "See only relevant work", body: "Give each partner a focused view of their activities, dates, locations, and dependencies." },
      { title: "Commit with confidence", body: "Confirm crew and completion expectations after prerequisites are visible." },
      { title: "Raise issues early", body: "Flag missing information, access, material, or predecessor work directly from the task." },
    ],
    workflow: [
      { title: "Review upcoming tasks", body: "See the work expected over the next several weeks." },
      { title: "Check readiness", body: "Confirm constraints and handoffs before accepting the commitment." },
      { title: "Update simply", body: "Report status, progress, photos, and issues from a phone." },
      { title: "Review reliability", body: "Use shared facts to improve coordination instead of assigning blame." },
    ],
    proof: { value: "No extra seats", label: "for project collaborators", title: "Coordination improves when every partner can participate.", body: "Agira is designed to bring trades into planning without turning participation into administrative overhead." },
  },
  "mid-market": {
    slug: "mid-market",
    section: "Solutions",
    group: "By size",
    title: "Mid-Market Contractors",
    headline: "Standardize the work without slowing the company down.",
    description: "Give growing project teams one repeatable planning system that is fast to adopt and strong enough to scale across the portfolio.",
    visual: "portfolio",
    visualLabel: "Growing portfolio workspace",
    outcomes: ["Fast team rollout", "Repeatable project controls", "Portfolio visibility"],
    highlights: [
      { title: "Start with real work", body: "Launch around active schedules and field planning instead of a long systems program." },
      { title: "Create one operating rhythm", body: "Use common lookahead, weekly planning, risk, and reporting workflows." },
      { title: "Scale with visibility", body: "See project health and adoption as the number of teams grows." },
    ],
    workflow: [
      { title: "Choose the standard", body: "Define a practical planning rhythm around how your best teams already operate." },
      { title: "Launch a project", body: "Connect the schedule and onboard project leaders and trade partners." },
      { title: "Measure adoption", body: "Track planning activity, reliability, and risk signals consistently." },
      { title: "Repeat with control", body: "Roll the proven setup into new projects without rebuilding it." },
    ],
    proof: { value: "Days", label: "to a live project workflow", title: "Growth needs consistency, not more reporting layers.", body: "Agira gives mid-market contractors the operating structure of a larger platform without the deployment weight." },
  },
  enterprise: {
    slug: "enterprise",
    section: "Solutions",
    group: "By size",
    title: "Enterprise",
    headline: "One planning standard across every project.",
    description: "Connect portfolio governance with project-level execution through consistent workflows, permissions, analytics, and integrations.",
    visual: "portfolio",
    visualLabel: "Enterprise portfolio control",
    outcomes: ["Portfolio standards", "Role-based governance", "Cross-project intelligence"],
    highlights: [
      { title: "Standardize the essentials", body: "Create repeatable planning, risk, milestone, and performance structures." },
      { title: "Keep project flexibility", body: "Let teams manage real project conditions within clear organizational controls." },
      { title: "Learn across the business", body: "Compare delivery signals and recurring causes across regions, teams, and project types." },
    ],
    workflow: [
      { title: "Define governance", body: "Set roles, templates, milestone standards, and required planning practices." },
      { title: "Connect systems", body: "Integrate the document and project systems teams already depend on." },
      { title: "Roll out by portfolio", body: "Launch with focused cohorts and measurable adoption targets." },
      { title: "Improve continuously", body: "Use operational analytics to refine standards and leadership support." },
    ],
    proof: { value: "One standard", label: "many project realities", title: "Enterprise control works when project teams can still execute.", body: "Agira connects consistent governance to the daily planning work where delivery outcomes are shaped." },
  },
  autodesk: {
    slug: "autodesk",
    section: "Solutions",
    group: "Integration",
    title: "Autodesk Construction Cloud",
    headline: "Bring drawings and schedule work into the same conversation.",
    description: "Connect Autodesk Construction Cloud documents with Agira planning so teams can reach current project context from the work itself.",
    visual: "integration",
    visualLabel: "Autodesk connected workflow",
    outcomes: ["Connected drawing context", "Fewer document searches", "Consistent project records"],
    highlights: [
      { title: "Connect the project", body: "Authorize an Autodesk project and select the document context your team needs." },
      { title: "Reach drawings from work", body: "Associate current sheets and files with activities, constraints, and coordination items." },
      { title: "Keep system ownership clear", body: "Use Autodesk for documents and Agira for connected planning context." },
    ],
    workflow: [
      { title: "Authorize securely", body: "Connect your Autodesk account through an organization administrator." },
      { title: "Map the project", body: "Choose the matching Agira and Autodesk project spaces." },
      { title: "Sync context", body: "Make relevant document references available inside planning workflows." },
      { title: "Work from one view", body: "Open the current source document from the schedule or issue that needs it." },
    ],
    proof: { value: "Connected", label: "not copied", title: "Teams should not have to choose between the plan and the document system.", body: "The Autodesk integration keeps each system focused while making project context easier to reach." },
  },
  procore: {
    slug: "procore",
    section: "Solutions",
    group: "Integration",
    title: "Procore",
    headline: "Connect project records to schedule consequence.",
    description: "Bring Procore RFIs and submittals into Agira planning so project teams can see which open records threaten upcoming work.",
    visual: "integration",
    visualLabel: "Procore connected workflow",
    outcomes: ["Linked RFIs and submittals", "Schedule-aware priorities", "Less duplicate entry"],
    highlights: [
      { title: "Keep Procore as record", body: "Continue managing formal project records in the system your teams already use." },
      { title: "Add schedule context", body: "Connect RFIs and submittals to affected activities and real need dates." },
      { title: "Prioritize by exposure", body: "See the document decisions most likely to affect near-term production." },
    ],
    workflow: [
      { title: "Connect Procore", body: "Authorize the company and choose the projects to link." },
      { title: "Sync project records", body: "Bring relevant RFI and submittal metadata into Agira." },
      { title: "Map affected work", body: "Associate records with schedule activities and constraints." },
      { title: "Coordinate resolution", body: "Use schedule exposure to focus follow-up while status stays synchronized." },
    ],
    proof: { value: "One link", label: "from record to planned work", title: "A project record becomes actionable when its schedule impact is visible.", body: "The Procore integration gives planning teams context without asking document-control teams to change their system of record." },
  },
};

export function getMarketingPage(section: "features" | "solutions", slug: string) {
  return section === "features" ? featurePages[slug] : solutionPages[slug];
}
