ALTER TYPE "AssistantActionKind" ADD VALUE 'TASK_PROGRESS_CHANGE';
ALTER TYPE "AssistantActionKind" ADD VALUE 'WEEKLY_COMMITMENT_CHANGE';

ALTER TABLE "task"
  ADD COLUMN "actualStartDate" TIMESTAMP(3),
  ADD COLUMN "actualFinishDate" TIMESTAMP(3);
